global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:9090']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:9090']

